
services:
  - type: web
    name: blog-system-website
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: "gunicorn blogpost.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0