# Generated by Django 6.0.6 on 2026-06-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_header', models.CharField(max_length=300)),
                ('blog_body', models.TextField()),
                ('author', models.CharField(max_length=150)),
                ('post_date', models.DateTimeField()),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
